# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f8f28a0f980edde71105244dc6d04ff9de9294bb55d34d76a2ff1084d37eee68833f764dc43409a097d36e6487b4d1f1e3ca1e789b3e7d8843f20bc51ec8d0a

test:
  secret_key_base: 8d93cfe0a2c3bc06f61e8f7552e510b568a82dcfe1c5a7fb4aab36c2a83b5178124d3a90b8ad7ccb3069895f5ead9772305267c416cbd2d8b26aebc86ce4b559

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
