# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bce90eb92c82abcb96b2b3c1af0396ce7756ce645c0b328ee2658131029f742f00f720795d757c0e7ad4a3c7d46629c69c4f4c50be40f35b1d204cc2f458d957

test:
  secret_key_base: dc8827b9f6b07e1e4c4059300e2894ebcaf57d7b5baf1f6370584282c1c5bcf6c0ebab882846a065224c69f7e33137692c3edb4501f648e2773ea32e1ef6498a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
