# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6abca1642cb24bf582847f667acb4537467f86e606c006b0637db7677812ee19532094d020359cf1ed805487d70e6bd3107f59914d44f0a27952c30ab39238ee

test:
  secret_key_base: eb6fe85369ec8baeee146fa0aad4efa0a2d9dc9b99d392f5d7408bc9fb5f3c16d3011087d8a313030ec9bdd2ddbf5f29759d09b4b42fbe68bdf9e341d955eac6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
